services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Biblioteca@25
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: unless-stopped

  biblioteca-backend:
    image: biblioteca-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5078:80"  # Mapeia a porta 80 do container para a 5078 local
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  sql_data:
  
networks:
  app-network:
    driver: bridge